### ISSUE TITLE
token transaction value vs balanceOf()

### ISSUE THREAD

**Issue by boosth** [carver/ethtoken.py#1] opened 2018-05-10 15:48 UTC
Does balanceOf() return the number of tokens for the individual transaction or the total number of tokens that have been transferred to the transaction address?

**Comment by carver** [comment] 2018-05-10 16:45
`balanceOf()` is a passthrough to the [the ERC20 standard method](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md#balanceof) (assuming the contract you load is compliant):

> Returns the account balance of another account with address `_owner`.
> 
> `function balanceOf(address _owner) view returns (uint256 balance)`

Note that this balance is *not* adjusted for [decimal places](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md#decimals), which is how the ERC20 spec works. 

If you want a token balance, adjusted for the number of decimals coded in the contract, then use [`token_balance()`](https://github.com/carver/ethtoken.py#custom-methods).

---

Closing because it's not a bug, but feel free to continue to comment for support.

**Closed by carver** 2018-05-10 16:45 UTC

**Comment by boosth** [comment] 2018-05-15 14:51
Is there a method for extracting the actual value of the specific contract?

It seems that token_balance() retrieves the value of all the tokens sent to a specific address rather than the specific value of an individual transaction.

ex.  If I use token_balance() to query this transaction I get a different value from the reported token transfer value on the webpage:  https://etherscan.io/tx/0x8c6441e94f0d8c6fc9ea76e8b25bebb477c6e2cab20b0e72f73c0c92c1f0fcb5

**Comment by boosth** [comment] 2018-05-15 15:59
def normalize_32_byte_hex_address(value):
    as_bytes = eth_utils.to_bytes(hexstr=value)
    return eth_utils.to_normalized_address(as_bytes[-20:])

**Comment by carver** [comment] 2018-05-15 16:50
Probably the ideal solution here is to use the [`Transfer`](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md#transfer-1) event. Web3.py will parse out the log for you so you can see the amount transferred. But if you have something working, then :+1:
